### ISSUE TITLE
transfer 

### ISSUE THREAD

**Issue by sz891016** [hfawaz/bigdata18#5]
Hello, I'm intested in your work. I want to know when you transfer the model which trained in source data to target data, you use all the target date to fine-tuning the model or just a part of it to fin-tuning it?
Look forward to your reply！
Thanks.

**Comment by hfawaz** [comment]
Hi, 

Thanks for your interest. 

For fine-tuning we did use all instances in the target dataset.

**Comment by sz891016** [comment]
I got it. Thanks for your reply!

**Comment by Hankinjing** [comment]
Hello, I'm intested in your work. your the compressed pre-trained models (without transfer learning) can't download.can you send my email y45180234@mail.ecust.edu.cn?
Look forward to your reply！
Thanks.

**Comment by hfawaz** [comment]
Hi, thanks for your interest. 

I am not sure of the problem because I am able to download them from my personal pc. 

This is the [link](http://supplementarymaterial.xyz/bigdata2018/pre-trained-models.tar.gz) that I am using. 

Maybe try a vpn or something ?

**Comment by monoregent** [comment]
Hello,
I installed the requirements shown, but as i try to run the code i get the error "ModuleNotFoundError: No module named 'distances.dtw.dtw'". How can i solve this problem? is it a requirement that's missing?

**Comment by hfawaz** [comment]
Hi, 

Thanks for the interest. 

It should be solved like [this](https://github.com/hfawaz/bigdata18/issues/1#issuecomment-440205466). 

Let me know if it works. 

Good luck.
