### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [hfawaz/bigdata18#6]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by hfawaz** [comment]
Hello, 

Thanks for your inquiry. 

But for now the current models do not work on a mixture of categorical and continuous data. 

Best,

**Comment by Sandy4321** [comment]
I see 
Thanks for soon answer
Relating to this and other your packages 
Will it work for multidimensional time series
Some call it multivariate time series
Let's say one dimension is categorical data 
(It can be transformed by one hot to numerical data)
And another dimension is continouse data
But scales are very different
And even inside one dimension scale is different
Let's say in very beginning signal is big and at the end is small

**Comment by hfawaz** [comment]
Okay thanks for this.

I think it may work, like implementation wise, but I am not sure how the network will deal with the inter-signal variations. 

I have never tried it, but I think it would be worth a try given your dataset.
