### ISSUE TITLE
Combined weights of all models

### ISSUE THREAD

**Issue by talhaanwarch** [hfawaz/bigdata18#7]
Is not is there any combined data set model. I am looking to classify EEG using transfer learning. But my query is that, all of your model are trained on seprate data set and have seprate weights.
Is not there any sort of cobined weight and architecture. Like we have in computer vision.

**Comment by hfawaz** [comment]
If I understood correctly, I would recommend checking out the work on domain adaptation maybe or semi-supervised learning , maybe this is a starting point.

**Comment by forestier** [comment]
Hi @talhaanwarch,

Thank you for your interest in our work.

Unlike computer vision, we do not have repositories of millions of annotated time series. Thus, the creation of a unique pre-trained model suitable for all applications is still an open issue for time series classification.

My advice would be use our method to compare your dataset to available UCR datasets (as described in our paper https://arxiv.org/abs/1811.01533) and to fine tune the most similar one with your data. My first guess would be the three ECG datasets of the UCR archive.

Let us know how it goes.

Best regards,

Germain
